# Generated by Django 5.2.1 on 2025-06-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('recepcao', 'Recepção'), ('triagem', 'Triagem'), ('medico', 'Médico')], max_length=10),
        ),
    ]
